name = "CoordinatedSupplyChains"
uuid = "3aaabd38-80f0-440d-8028-ff5345734cd4"
authors = ["Philip A Tominac <tominac@wisc.edu> and contributors"]
version = "0.2.0"

[deps]
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
Clp = "1"
JuMP = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
